version: "3"
services:
  springboot-app:
    container_name: hospital-doctor-data
    image: springboot-hospital-data-app
    restart: always 
    
    build: .
    ports:
      - 9111:9111
    environment: 
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
      
      
      
  mysqldb:
    container_name: mysqldb 
    image: mysql
    volumes:
      - C:\Users\mindc1july10\Desktop\DockerDB:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: Doctordb
      MYSQL_ROOT_PASSWORD: root
    