spring:
 datasource: 
    url: jdbc:sqlserver://doctor-data.database.windows.net:1433;database=doctordb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    
    username: doctordata
    password: Aniket@123
    
    
 jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect
server:
  port: 9111      
      
      